// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqg9wGHdJa7CKHPGv4FPeQzMF9Z6c6fOw',
    appId: '1:411579471229:web:975110aeaa9728cca0e814',
    messagingSenderId: '411579471229',
    projectId: 'refrigerator-care',
    authDomain: 'refrigerator-care.firebaseapp.com',
    storageBucket: 'refrigerator-care.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqg9wGHdJa7CKHPGv4FPeQzMF9Z6c6fOw',
    appId: '1:411579471229:android:975110aeaa9728cca0e814',
    messagingSenderId: '411579471229',
    projectId: 'refrigerator-care',
    storageBucket: 'refrigerator-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqg9wGHdJa7CKHPGv4FPeQzMF9Z6c6fOw',
    appId: '1:411579471229:ios:975110aeaa9728cca0e814',
    messagingSenderId: '411579471229',
    projectId: 'refrigerator-care',
    storageBucket: 'refrigerator-care.firebasestorage.app',
    iosClientId: '411579471229-isqa8gft0r8ctikpjstghf90e5q4v20p.apps.googleusercontent.com',
    iosBundleId: 'com.example.coldguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqg9wGHdJa7CKHPGv4FPeQzMF9Z6c6fOw',
    appId: '1:411579471229:ios:975110aeaa9728cca0e814',
    messagingSenderId: '411579471229',
    projectId: 'refrigerator-care',
    storageBucket: 'refrigerator-care.firebasestorage.app',
    iosClientId: '411579471229-isqa8gft0r8ctikpjstghf90e5q4v20p.apps.googleusercontent.com',
    iosBundleId: 'com.example.coldguard',
  );
} 